### ISSUE TITLE
Deployed front-end doesn't reload to include latest data

### ISSUE THREAD

**Issue by kairstenfay** [seattleflu/scan-switchboard#10]
It's unclear at this point whether this is a deployment configuration issue (and thus should be filed at seattleflu/backoffice) or something that can be fixed in this repo. 

In the past couple of days, the deployed app at backoffice.seattleflu.org/switchboard has failed to update the front-end with the latest data in the sqlite database. 

See [this Slack thread](https://seattle-flu-study.slack.com/archives/CCAA9RBFS/p1593797493174500?thread_ts=1593793195.173700&cid=CCAA9RBFS) for the steps I took to debug, as I'm unsure how much barcode/REDCap link sharing I should be doing in a public setting.

**Comment by kairstenfay** [comment]
From @tsibley:
> My guess is that this issue is related to how we're updating the SQLite file. Particularly if Datasette holds open file handles to it.
> 
> If we can replicate locally, then using `lsof` to look at the inodes the Datasette processes have open and comparing to the inode of the latest SQLite file would be helpful next time this occurs.

**Comment by tsibley** [comment]
Reproducing locally might also be easier by running Datasette single-threaded so that test requests are sure to hit the same process/thread.

In this code:

https://github.com/seattleflu/scan-switchboard/blob/92a9a9ecbbe9e035f51821bad60fd611d79e1ade/Makefile#L6-L8

We're not updating the SQLite file in place, but replacing it with a different file.

**Comment by tsibley** [comment]
Fortuitously, this just happened again in production. I grabbed an `lsof` snapshot of the Datasette process (PID reported by `systemctl status scan-switchboard`) and `stat`'d the current SQLite file.

![image](https://user-images.githubusercontent.com/79913/86621533-3506be00-bf73-11ea-877e-3e344e52b77c.png)

The current SQLite file is inode 2560088, and as suspected, the Datasette threads are still holding open file descriptors for the deleted files. `lsof` helpfully reports this, but you can also see the inodes (last number before the file path) are different (2560067 and 2560061). They're not even consistent across threads, since the threads presumably opened the path at different times.

I think in-place updates will work if we stop re-creating/overwriting the database file everytime but instead only update it in-place via SQL commands.

**Comment by joverlee521** [comment]
Can we just update in-place via `cp`?
```
cp $@.new $@
rm $@.new
```

**Comment by kairstenfay** [comment]
Working on this now, but wanted to say that reverting commit `de07e5c42c31c3650dcf3f8e65e1a0db0cb548f7` produces the same error (of datasette pointing to a deleted sqlite file). 

Same goes for @joverlee521's cp/rm suggestion, unfortunately.

**Comment by kairstenfay** [comment]
If I understand @tsibley correctly, updating the sqlite file in place also results in the same error.
```
data/scan-redcap.sqlite: data/record-barcodes.ndjson derived-tables.sql
	sqlite-utils insert --nl $@ record_barcodes $<
	sqlite3 $@ < derived-tables.sql
```

**Comment by kairstenfay** [comment]
Ah, my original testing process was flawed. It appears both @joverlee521's solution, 
```
data/scan-redcap.sqlite: data/record-barcodes.ndjson derived-tables.sql
	sqlite-utils insert --nl $@.new record_barcodes $<
	sqlite3 $@.new < derived-tables.sql
	cp $@.new $@
	rm $@.new
```
, and updating in place (my code in the previous comment) avoid Datasette threads' holding open file descriptors of deleted files.

**Comment by kairstenfay** [comment]
Description of my local testing:
1. restart the service with `systemctl restart scan-switchboard`
2. run `make -B` but with a project, e.g. SCAN IRB English, removed. 
3. run `make -B` again but including the project removed in #2. 
4. see if the web app can access the newly included data

**Comment by tsibley** [comment]
Testing with Datasette using multiple threads is likely to give misleading results, as your different requests may hit different threads which only open the SQLite file as necessary. This is why different threads in the `lsof` output above had different inodes opened.

Using `cp` instead is a good thought! But I'm wary of overwriting the entire SQLite file in-place, as that may modify other parts of the SQLite file structure behind Datasette's back and lead to other subtle issues. Depending on how the SQLite libraries handle this, it might be ok, but I don't know SQLite's guarantees here.

One option might be to leave the SQLite file itself alone and instead do the replacement atomically within SQL. That is, within a single transaction, `truncate` the data table before `insert`. I added support to `sqlite-utils` for this [yesterday in a PR](https://github.com/simonw/sqlite-utils/pull/118), thinking we might need it.

**Comment by tsibley** [comment]
The [`num_sql_threads` option](https://datasette.readthedocs.io/en/stable/config.html#num-sql-threads) to Datasette allows specifying how many Python threads are used to open the SQLite file and run queries. If I set it to 1 by:

```
pipenv run ./bin/serve --config num_sql_threads:1
```

then overwrite the file in-place with `cp` and make a new request, I see this error in the logs:

```
ERROR: conn=<sqlite3.Connection object at 0x7f27e1bfd1f0>, sql = 'select count(*) from [duplicate_record_ids]', params = None: database disk image is malformed
```

**Comment by kairstenfay** [comment]
> The [`num_sql_threads` option](https://datasette.readthedocs.io/en/stable/config.html#num-sql-threads) to Datasette allows specifying how many Python threads are used to open the SQLite file and run queries. If I set it to 1 by:
> 
> ```
> pipenv run ./bin/serve --config num_sql_threads:1
> ```
> 
> then overwrite the file in-place with `cp` and make a new request, I see this error in the logs:
> 
> ```
> ERROR: conn=<sqlite3.Connection object at 0x7f27e1bfd1f0>, sql = 'select count(*) from [duplicate_record_ids]', params = None: database disk image is malformed
> ```

Hey Tom, where do you see this error? I invoked ./bin/serve with the `num_sql_threads` option, and I don't see that error logged in my syslog, systemctl or journalctl status outputs.

**Comment by tsibley** [comment]
It's in the terminal output when I run

```
pipenv run ./bin/serve --config num_sql_threads:1
```
